# Generated by Django 4.1.3 on 2022-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='birthdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
