# Generated by Django 4.1.3 on 2022-12-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
