# Generated by Django 4.1.3 on 2022-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_members_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date',
            field=models.DateField(),
        ),
    ]
