# Generated by Django 4.1.3 on 2022-12-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='members',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
