# Generated by Django 4.1.3 on 2023-01-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='byte',
            field=models.BinaryField(max_length=4),
        ),
    ]
