# Generated by Django 4.1.3 on 2023-01-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_alter_blog_byte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('b', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
