# Generated by Django 4.1.3 on 2023-01-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_book_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='teacher',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='members.teacher'),
        ),
    ]
