# Generated by Django 4.1.3 on 2023-01-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_members_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='www', max_length=50, primary_key=True, serialize=False),
        ),
    ]
