# Generated by Django 4.1.3 on 2023-01-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='mgh', max_length=50, primary_key=True, serialize=False),
        ),
    ]
