# Generated by Django 4.1.3 on 2023-01-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b',
            field=models.BooleanField(default=None),
        ),
    ]
