# Generated by Django 4.1.3 on 2023-01-02 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_alter_members_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 2)),
        ),
    ]
