# Generated by Django 4.1.3 on 2023-01-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_alter_members_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=5),
        ),
    ]
