# Generated by Django 4.1.3 on 2023-01-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
