# Generated by Django 4.1.3 on 2023-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
